# Generated by Django 5.2.5 on 2025-08-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='turma',
            field=models.CharField(max_length=50),
        ),
    ]
